(cl:in-package #:vellum.plot)


(defgeneric data-layer (stack))
(defgeneric aesthetics-layer (stack))
(defgeneric scale-layer (stack))
(defgeneric geometrics-layer (stack))
(defgeneric statistics-layer (stack))
(defgeneric facets-layer (stack))
(defgeneric coordinates-layer (stack))
(defgeneric x (aesthetics-layer))
(defgeneric y (aesthetics-layer))
(defgeneric color (aesthetics-layer))
(defgeneric shape (aesthetics-layer))
(defgeneric size (aesthetics-layer))
(defgeneric label (aesthetics-layer))
(defgeneric mapping (geometrics))
(defgeneric visualize (backend stack destination))
(defgeneric add (stack layer))
(defgeneric layer-category (layer))
